[WIP] i40e driver
ix-project/ix pull request #6
Opened 2016-11-11 00:19 UTC by aroulin

Rebased on the `driver-common` PR that needs to be merged first.
WIP as I'll add the commits as I clean them.

2016-11-11 16:35 UTC, aroulin commented on dp/drivers/i40e.c
> +	dev_info->nb_rx_fgs = 128;
Not sure about that line. Copied from `ixgbe.c`. Is it related to RSS or is it IX-specific?

2016-11-11 17:24 UTC, aroulin commented on dp/drivers/i40e.c
> +#define I40E_MAC_X722_VF 8 //FIXME
w/o that line:
```
In file included from drivers/i40e.c:40:0:
../deps/dpdk/drivers/net/i40e/i40e_ethdev.h: In function 'i40e_get_vsi_from_adapter':
../deps/dpdk/drivers/net/i40e/i40e_ethdev.h:617:53: error: 'I40E_MAC_X722_VF' undeclared (first use in this function)
  if (hw->mac.type == I40E_MAC_VF || hw->mac.type == I40E_MAC_X722_VF) ```

2016-11-11 17:24 UTC, aroulin commented on dp/drivers/i40e.c
> +	ret = rte_eth_rx_queue_setup(dev->port, queue_idx, nb_desc, numa_node, &rx_conf, dpdk_pool);
Using global `rx_conf` here. Need to check it works as I accidentally was using a zero-filled default conf (and it worked surprisingly!). We can also use `NULL` and have dpdk use a default one.

2016-11-11 17:24 UTC, aroulin commented on dp/drivers/i40e.c
> +	//i40e_dev_rx_queue_release(drxq);
Do we want to free dpdk's queue?

2016-11-11 18:22 UTC, prekageo commented on dp/drivers/i40e.c
> +	dev_info->nb_rx_fgs = 128;
It is related to RSS. It is hardware-specific. ixgbe has 128 flow groups. How many does the i40e has? Can we get this number using a DPDK API call?

2016-11-11 18:25 UTC, prekageo commented on dp/drivers/i40e.c
> +#define I40E_MAC_X722_VF 8 //FIXME
Maybe you are not `#include`ing something? Copy-pasting a `#define` should be our last resort. Maybe you need to say `#define X722_SUPPORT` (move it from the gcc command line here)? But is it necessary?

2016-11-11 18:29 UTC, prekageo commented on dp/drivers/i40e.c
> +	ret = rte_eth_rx_queue_setup(dev->port, queue_idx, nb_desc, numa_node, &rx_conf, dpdk_pool);
Using `NULL` sounds fine. Unless, IX needs to pass some specific configuration options that are not DPDK's default options. Is that the case?

2016-11-11 18:30 UTC, prekageo commented on dp/drivers/i40e.c
> +	//i40e_dev_rx_queue_release(drxq);
That's a good idea. Unless it breaks something in a weird way. If it works correctly, then you could to do the same in the ixgbe driver later on.

2016-11-11 23:14 UTC, aroulin commented on dp/drivers/i40e.c
> +	dev_info->nb_rx_fgs = 128;
Do I understand correctly that this is the RETA size? We can get it with `dev_infos` http://dpdk.org/doc/api/structrte__eth__dev__info.html#a8f02d328521addc69743ec44f124065c

2016-11-12 13:44 UTC, prekageo commented on dp/drivers/i40e.c
> +	dev_info->nb_rx_fgs = 128;
Yes, that's correct. I guess we should get this information from it. I also hope that DPDK returns 128 for the ixgbe.

2016-11-13 04:20 UTC, aroulin commented on dp/drivers/i40e.c
> -	dev_info->nb_rx_fgs = dpdk_dev_info.reta_size;
This returns 512.
It seems it causes the following function to overflow and zero out fields of the queue (drv_rx_queue is null after it).
https://github.com/aroulin/ix/blob/i40e-driver-release/dp/core/ethdev.c#L260

Need to debug that. With 128 it works fine.

2016-11-13 11:12 UTC, prekageo commented on dp/drivers/i40e.c
> -	dev_info->nb_rx_fgs = dpdk_dev_info.reta_size;
Check out this: https://github.com/ix-project/ix/blob/bd4dd0ba200413716071561a3c3f2994159c665d/inc/ix/ethfg.h#L38

There is an upper limit on the number of flow groups that IX supports. Try to raise it,

2016-11-15 10:22 UTC, aroulin commented
`ETH_RSS_RETA_NUM_ENTRIES` would need to be dynamically changed depending on the driver (`ixgbe` or `i40e`).
https://github.com/ix-project/ix/blob/bd4dd0ba200413716071561a3c3f2994159c665d/inc/ix/ethdev.h#L225

2016-11-15 10:29 UTC, aroulin commented on dp/drivers/i40e.c
> +	ret = r_dev.dev_ops->reta_update(&r_dev, r_reta_conf, ETH_RSS_RETA_NUM_ENTRIES);
ETH_RSS_RETA_NUM_ENTRIES would need to be dynamically changed depending on the driver (ixgbe or i40e).
https://github.com/ix-project/ix/blob/bd4dd0ba200413716071561a3c3f2994159c665d/inc/ix/ethdev.h#L225

2016-11-15 10:42 UTC, aroulin commented on dp/drivers/i40e.c
> +	struct rte_eth_rss_reta_entry64 r_reta_conf[2];
I supposed this `2` is a magic number that should be changed to `ETH_RSS_RETA_NUM_ENTRIES / 64`

2016-11-15 10:42 UTC, prekageo commented on inc/ix/ethqueue.h
> +	void *drv_tx_queue; /*pointer to driver queue data*/
I understand that you use the field `drv_tx_queue` to access the `tx_queue` from the `eth_tx_queue`. You don't need this field. Take a look at the definition of `tx_queue`:

```
struct tx_queue {
    struct eth_tx_queue etxq;
    ...
}
```

`tx_queue` contains an `eth_tx_queue`. That means that given an `eth_tx_queue` you can get a `tx_queue` by using a `container_of` trick/macro.

2016-11-15 10:43 UTC, prekageo commented on inc/ix/ethqueue.h
> +	void *drv_rx_queue; /*pointer to driver queue data*/
Same comment as below.

2016-11-15 10:55 UTC, aroulin commented on inc/ix/ethqueue.h
> +	void *drv_tx_queue; /*pointer to driver queue data*/
right, it's fixed now.

2016-11-15 10:55 UTC, aroulin commented on inc/ix/ethqueue.h
> +	void *drv_rx_queue; /*pointer to driver queue data*/
fixed too.

2016-11-15 11:17 UTC, aroulin commented on dp/drivers/i40e.c
> +	ret = r_dev.dev_ops->reta_update(&r_dev, r_reta_conf, ETH_RSS_RETA_NUM_ENTRIES);
In order to handle a RETA table of size 512, this struct would need to be modified too:
https://github.com/ix-project/ix/blob/master/inc/ix/ethdev.h#L296.

2016-11-16 08:16 UTC, aroulin commented on inc/ix/ethdev.h
>  #define ETH_RSS_RETA_MAX_QUEUE   16
Is `ETH_RSS_RETA_MAX_QUEUE` IX-specific or related to the driver? It is used here:
https://github.com/aroulin/ix/blob/i40e-driver-release/dp/core/ethdev.c#L100
 
i40e DPDK driver says `dev_info.max_rx_queues` is 320 which is quite higher than 16.

2016-11-16 09:05 UTC, prekageo commented on inc/ix/ethdev.h
>  #define ETH_RSS_RETA_MAX_QUEUE   16
Changing the `#define` from 128 to 512 doesn't seem like the right thing to do. Remember, that IX must work both with ixgbe (which has 128 entries) and i40e (which has 512 entries). You should remove the `#define` and implement a different configuration scheme.

2016-11-16 09:09 UTC, prekageo commented on inc/ix/ethdev.h
>  #define ETH_RSS_RETA_MAX_QUEUE   16
As for the `ETH_RSS_RETA_MAX_QUEUE`, IX wants an RX queue per thread. I am not sure that we have a good reason for capping the number of queues to 16 except that our servers have 16 HTs. Don't worry about it for this pull request. We might want to make it more flexible (support servers with more HTs) later on, though.

2016-11-16 09:18 UTC, aroulin commented on inc/ix/ethdev.h
>  #define ETH_RSS_RETA_MAX_QUEUE   16
of course for the `#define ETH_RSS_RETA_NUM_ENTRIES`. I was just trying it to see if it works. It does give `0 <= fg_id < 512`

2016-11-16 11:52 UTC, aroulin commented on inc/ix/ethdev.h
> +struct ix_rte_eth_rss_reta_entry64 {
This is the same definition as in DPDK
http://dpdk.org/doc/api/structrte__eth__rss__reta__entry64.html

2016-11-16 11:54 UTC, aroulin commented on dp/core/ethfg.c
> +		*rss_reta = malloc(ETH_RSS_RETA_NUM_GROUPS(fg->eth) * sizeof(struct ix_rte_eth_rss_reta_entry64));
Need to figure out exactly where we want to allocate the dynamically-sized `rss_reta` array + check return value.

2016-11-17 16:14 UTC, prekageo requested changes

2016-11-17 16:14 UTC, prekageo commented on dp/core/dpdk.c
> -	internal_config.no_hugetlbfs = 1;
Apparently the initialization of the i40e in DPDK requires huge pages, so I understand the reason for this change. However, I've noticed that the boot time of IX has increased after removing this line. Can you investigate if we can initialize the i40e without removing this line?

2016-11-17 16:14 UTC, prekageo commented on dp/drivers/i40e.c
> +static void mac_addr_add(struct ix_rte_eth_dev *dev, struct eth_addr *mac_addr, uint32_t index, uint32_t vmdq)
There is code duplication. This function is the same as https://github.com/ix-project/ix/blob/master/dp/drivers/ixgbe.c#L857. Can you please identify the duplicated functions between these two files? Then, please move them to https://github.com/ix-project/ix/blob/master/dp/drivers/common.c. I'd like to see a separate pull request where you refactor ixgbe.c in that way.

2016-11-18 01:40 UTC, aroulin commented on dp/core/dpdk.c
> -	internal_config.no_hugetlbfs = 1;
I'll investigate.

2016-11-29 15:42 UTC, prekageo approved these changes

2016-11-29 15:48 UTC, merged